site_name: UC Berkeley CAS Documentation
theme: readthedocs
repo_url: https://github.com/bwood/ucberkeley_cas-7
pages:
  - Home: index.md
  - LDAP Access: ldap_access.md
  - FAQ: faq.md
markdown_extensions:
    - admonition: